In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X = scaler.fit_transform(X)

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [ ]:
model = Sequential()

model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6287 - loss: 0.6574 - val_accuracy: 0.7143 - val_loss: 0.6151
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5893 - val_accuracy: 0.7792 - val_loss: 0.5584
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5447 - val_accuracy: 0.7922 - val_loss: 0.5179
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5146 - val_accuracy: 0.8052 - val_loss: 0.4901
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4948 - val_accuracy: 0.8182 - val_loss: 0.4695
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4803 - val_accuracy: 0.8247 - val_loss: 0.4546
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4696 - val_accuracy: 0.8312 - val_loss: 0.4422
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4604 - val_accuracy: 0.8312 - val_loss: 0.4323
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4530 - val_accuracy: 0.8312 - val_loss: 0.4250
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4469 - val_accuracy: 0.8312 - val_loss: 0.4174
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4413 - val_accuracy: 0.8377 - val_loss: 0.4125
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4372 - val_accuracy: 0.8247 - val_loss: 0.4078
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4318 - val_accuracy: 0.8247 - val_loss: 0.4042
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4284 - val_accuracy: 0.8182 - val_loss: 0.4006
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4246 - val_accuracy: 0.8182 - val_loss: 0.3972
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4211 - val_accuracy: 0.8117 - val_loss: 0.3944
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4180 - val_accuracy: 0.8117 - val_loss: 0.3919
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4152 - val_accuracy: 0.8247 - val_loss: 0.3895
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4112 - val_accuracy: 0.8247 - val_loss: 0.3885
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4088 - val_accuracy: 0.8182 - val_loss: 0.3871
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4056 - val_accuracy: 0.8182 - val_loss: 0.3849
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4027 - val_accuracy: 0.8182 - val_loss: 0.3820
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4001 - val_accuracy: 0.8117 - val_loss: 0.3808
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3972 - val_accuracy: 0.8117 - val_loss: 0.3789
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3947 - val_accuracy: 0.8182 - val_loss: 0.3774
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3922 - val_accuracy: 0.8117 - val_loss: 0.3754
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.3895 - val_accuracy: 0.8117 - val_loss: 0.3735
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3871 - val_accuracy: 0.8182 - val_loss: 0.3713
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3852 - val_accuracy: 0.8182 - val_loss: 0.3703
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3821 - val_accuracy: 0.8247 - val_loss: 0.3687
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3800 - val_accuracy: 0.8312 - val_loss: 0.3676
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3779 - val_accuracy: 0.8247 - val_loss: 0.3660
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3746 - val_accuracy: 0.8312 - val_loss: 0.3641
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3723 - val_accuracy: 0.8247 - val_loss: 0.3628
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3699 - val_accuracy: 0.8182 - val_loss: 0.3611
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3673 - val_accuracy: 0.8247 - val_loss: 0.3609
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3650 - val_accuracy: 0.8377 - val_loss: 0.3584
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3630 - val_accuracy: 0.8506 - val_loss: 0.3571
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3608 - val_accuracy: 0.8506 - val_loss: 0.3548
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3583 - val_accuracy: 0.8506 - val_loss: 0.3531
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3560 - val_accuracy: 0.8506 - val_loss: 0.3521
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3537 - val_accuracy: 0.8506 - val_loss: 0.3505
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3519 - val_accuracy: 0.8506 - val_loss: 0.3495
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3499 - val_accuracy: 0.8506 - val_loss: 0.3482
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3475 - val_accuracy: 0.8636 - val_loss: 0.3492
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8583 - loss: 0.3452 - val_accuracy: 0.8636 - val_loss: 0.3479
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8599 - loss: 0.3434 - val_accuracy: 0.8636 - val_loss: 0.3488
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8599 - loss: 0.3415 - val_accuracy: 0.8571 - val_loss: 0.3480
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8648 - loss: 0.3397 - val_accuracy: 0.8636 - val_loss: 0.3466
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3378 - val_accuracy: 0.8571 - val_loss: 0.3455
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3356 - val_accuracy: 0.8636 - val_loss: 0.3444
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8632 - loss: 0.3338 - val_accuracy: 0.8636 - val_loss: 0.3424
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8648 - loss: 0.3324 - val_accuracy: 0.8636 - val_loss: 0.3404
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8632 - loss: 0.3304 - val_accuracy: 0.8701 - val_loss: 0.3402
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8648 - loss: 0.3290 - val_accuracy: 0.8701 - val_loss: 0.3400
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3274 - val_accuracy: 0.8701 - val_loss: 0.3395
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3257 - val_accuracy: 0.8766 - val_loss: 0.3396
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8697 - loss: 0.3243 - val_accuracy: 0.8701 - val_loss: 0.3380
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8713 - loss: 0.3233 - val_accuracy: 0.8701 - val_loss: 0.3375
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3214 - val_accuracy: 0.8636 - val_loss: 0.3387
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8746 - loss: 0.3209 - val_accuracy: 0.8636 - val_loss: 0.3383
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3196 - val_accuracy: 0.8701 - val_loss: 0.3377
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8762 - loss: 0.3182 - val_accuracy: 0.8701 - val_loss: 0.3378
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8762 - loss: 0.3169 - val_accuracy: 0.8701 - val_loss: 0.3383
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8762 - loss: 0.3163 - val_accuracy: 0.8701 - val_loss: 0.3369
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8762 - loss: 0.3153 - val_accuracy: 0.8766 - val_loss: 0.3355
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3150 - val_accuracy: 0.8571 - val_loss: 0.3343
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3134 - val_accuracy: 0.8766 - val_loss: 0.3348
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3127 - val_accuracy: 0.8766 - val_loss: 0.3346
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8795 - loss: 0.3120 - val_accuracy: 0.8766 - val_loss: 0.3349
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3112 - val_accuracy: 0.8701 - val_loss: 0.3349
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3107 - val_accuracy: 0.8636 - val_loss: 0.3371
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3097 - val_accuracy: 0.8636 - val_loss: 0.3383
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.3091 - val_accuracy: 0.8636 - val_loss: 0.3414
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3081 - val_accuracy: 0.8701 - val_loss: 0.3402
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3075 - val_accuracy: 0.8701 - val_loss: 0.3397
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.3070 - val_accuracy: 0.8701 - val_loss: 0.3377
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3059 - val_accuracy: 0.8701 - val_loss: 0.3395
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3053 - val_accuracy: 0.8701 - val_loss: 0.3382
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3046 - val_accuracy: 0.8701 - val_loss: 0.3372
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3046 - val_accuracy: 0.8766 - val_loss: 0.3381
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3036 - val_accuracy: 0.8701 - val_loss: 0.3382
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3030 - val_accuracy: 0.8701 - val_loss: 0.3376
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3025 - val_accuracy: 0.8766 - val_loss: 0.3368
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3019 - val_accuracy: 0.8701 - val_loss: 0.3372
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3018 - val_accuracy: 0.8701 - val_loss: 0.3367
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3009 - val_accuracy: 0.8831 - val_loss: 0.3377
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3008 - val_accuracy: 0.8701 - val_loss: 0.3389
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.3001 - val_accuracy: 0.8766 - val_loss: 0.3422
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.2994 - val_accuracy: 0.8766 - val_loss: 0.3408
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2991 - val_accuracy: 0.8766 - val_loss: 0.3417
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.2987 - val_accuracy: 0.8896 - val_loss: 0.3416
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.2984 - val_accuracy: 0.8766 - val_loss: 0.3406
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2978 - val_accuracy: 0.8831 - val_loss: 0.3401
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.2973 - val_accuracy: 0.8831 - val_loss: 0.3403
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2969 - val_accuracy: 0.8896 - val_loss: 0.3405
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2971 - val_accuracy: 0.8831 - val_loss: 0.3420
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.2968 - val_accuracy: 0.8831 - val_loss: 0.3415
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2958 - val_accuracy: 0.8831 - val_loss: 0.3423
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.2955 - val_accuracy: 0.8766 - val_loss: 0.3400

In [ ]:
# how to select appropriate optimizer
# No. of nodes in a layer
# how to select number of layers
# All in all one model

In [ ]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 6.8 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.3896103799343109

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 19s

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7443 - loss: 0.4968 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4774 - val_accuracy: 0.8377 - val_loss: 0.4500
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4647 - val_accuracy: 0.8442 - val_loss: 0.4375
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4547 - val_accuracy: 0.8377 - val_loss: 0.4285
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7866 - loss: 0.4482 - val_accuracy: 0.8312 - val_loss: 0.4226
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4415 - val_accuracy: 0.8312 - val_loss: 0.4150
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7818 - loss: 0.4366 - val_accuracy: 0.8377 - val_loss: 0.4110
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7899 - loss: 0.4318 - val_accuracy: 0.8377 - val_loss: 0.4055
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7899 - loss: 0.4275 - val_accuracy: 0.8442 - val_loss: 0.4016
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.8442 - val_loss: 0.4005
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7964 - loss: 0.4199 - val_accuracy: 0.8377 - val_loss: 0.3973
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7980 - loss: 0.4162 - val_accuracy: 0.8442 - val_loss: 0.3931
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7997 - loss: 0.4125 - val_accuracy: 0.8442 - val_loss: 0.3908
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.4092 - val_accuracy: 0.8442 - val_loss: 0.3885
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8029 - loss: 0.4063 - val_accuracy: 0.8442 - val_loss: 0.3848
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8029 - loss: 0.4031 - val_accuracy: 0.8506 - val_loss: 0.3824
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8062 - loss: 0.4000 - val_accuracy: 0.8506 - val_loss: 0.3806
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8127 - loss: 0.3969 - val_accuracy: 0.8571 - val_loss: 0.3791
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3938 - val_accuracy: 0.8571 - val_loss: 0.3766
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8160 - loss: 0.3911 - val_accuracy: 0.8571 - val_loss: 0.3751
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8192 - loss: 0.3884 - val_accuracy: 0.8571 - val_loss: 0.3737
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8241 - loss: 0.3854 - val_accuracy: 0.8571 - val_loss: 0.3709
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8274 - loss: 0.3834 - val_accuracy: 0.8636 - val_loss: 0.3690
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8355 - loss: 0.3807 - val_accuracy: 0.8636 - val_loss: 0.3669
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8355 - loss: 0.3782 - val_accuracy: 0.8636 - val_loss: 0.3649
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8371 - loss: 0.3747 - val_accuracy: 0.8571 - val_loss: 0.3656
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8404 - loss: 0.3719 - val_accuracy: 0.8571 - val_loss: 0.3655
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8436 - loss: 0.3689 - val_accuracy: 0.8571 - val_loss: 0.3625
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8388 - loss: 0.3661 - val_accuracy: 0.8636 - val_loss: 0.3598
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8388 - loss: 0.3635 - val_accuracy: 0.8636 - val_loss: 0.3579
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8404 - loss: 0.3605 - val_accuracy: 0.8701 - val_loss: 0.3561
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3579 - val_accuracy: 0.8701 - val_loss: 0.3548
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3557 - val_accuracy: 0.8701 - val_loss: 0.3534
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3527 - val_accuracy: 0.8636 - val_loss: 0.3521
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3501 - val_accuracy: 0.8766 - val_loss: 0.3503
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3478 - val_accuracy: 0.8701 - val_loss: 0.3489
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3453 - val_accuracy: 0.8701 - val_loss: 0.3472
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8599 - loss: 0.3428 - val_accuracy: 0.8701 - val_loss: 0.3465
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8632 - loss: 0.3409 - val_accuracy: 0.8701 - val_loss: 0.3457
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8664 - loss: 0.3391 - val_accuracy: 0.8701 - val_loss: 0.3434
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3371 - val_accuracy: 0.8701 - val_loss: 0.3439
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8730 - loss: 0.3355 - val_accuracy: 0.8701 - val_loss: 0.3427
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8730 - loss: 0.3337 - val_accuracy: 0.8701 - val_loss: 0.3433
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8730 - loss: 0.3318 - val_accuracy: 0.8701 - val_loss: 0.3424
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8795 - loss: 0.3298 - val_accuracy: 0.8506 - val_loss: 0.3444
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.3289 - val_accuracy: 0.8506 - val_loss: 0.3447
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8811 - loss: 0.3274 - val_accuracy: 0.8571 - val_loss: 0.3445
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8779 - loss: 0.3257 - val_accuracy: 0.8766 - val_loss: 0.3430
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8762 - loss: 0.3242 - val_accuracy: 0.8636 - val_loss: 0.3426
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8811 - loss: 0.3231 - val_accuracy: 0.8636 - val_loss: 0.3427
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.3217 - val_accuracy: 0.8701 - val_loss: 0.3413
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8860 - loss: 0.3205 - val_accuracy: 0.8766 - val_loss: 0.3411
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8844 - loss: 0.3195 - val_accuracy: 0.8636 - val_loss: 0.3443
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3184 - val_accuracy: 0.8636 - val_loss: 0.3441
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8860 - loss: 0.3174 - val_accuracy: 0.8636 - val_loss: 0.3451
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3167 - val_accuracy: 0.8636 - val_loss: 0.3433
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3157 - val_accuracy: 0.8636 - val_loss: 0.3427
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3145 - val_accuracy: 0.8571 - val_loss: 0.3436
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3139 - val_accuracy: 0.8636 - val_loss: 0.3431
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3128 - val_accuracy: 0.8571 - val_loss: 0.3428
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3119 - val_accuracy: 0.8636 - val_loss: 0.3469
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.3111 - val_accuracy: 0.8636 - val_loss: 0.3450
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.3100 - val_accuracy: 0.8636 - val_loss: 0.3480
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.3097 - val_accuracy: 0.8571 - val_loss: 0.3497
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3086 - val_accuracy: 0.8571 - val_loss: 0.3486
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3082 - val_accuracy: 0.8636 - val_loss: 0.3452
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.3071 - val_accuracy: 0.8636 - val_loss: 0.3454
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.3070 - val_accuracy: 0.8636 - val_loss: 0.3452
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3063 - val_accuracy: 0.8636 - val_loss: 0.3456
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.3052 - val_accuracy: 0.8636 - val_loss: 0.3484
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.3046 - val_accuracy: 0.8636 - val_loss: 0.3474
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3041 - val_accuracy: 0.8636 - val_loss: 0.3467
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3033 - val_accuracy: 0.8636 - val_loss: 0.3483
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3030 - val_accuracy: 0.8636 - val_loss: 0.3490
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3024 - val_accuracy: 0.8571 - val_loss: 0.3503
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3016 - val_accuracy: 0.8571 - val_loss: 0.3519
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3014 - val_accuracy: 0.8571 - val_loss: 0.3537
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.3009 - val_accuracy: 0.8506 - val_loss: 0.3552
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.3007 - val_accuracy: 0.8506 - val_loss: 0.3548
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2999 - val_accuracy: 0.8506 - val_loss: 0.3528
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2998 - val_accuracy: 0.8571 - val_loss: 0.3511
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2992 - val_accuracy: 0.8571 - val_loss: 0.3507
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2982 - val_accuracy: 0.8571 - val_loss: 0.3507
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.2980 - val_accuracy: 0.8571 - val_loss: 0.3507
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2974 - val_accuracy: 0.8571 - val_loss: 0.3516
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2977 - val_accuracy: 0.8571 - val_loss: 0.3471
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2972 - val_accuracy: 0.8636 - val_loss: 0.3468
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2972 - val_accuracy: 0.8571 - val_loss: 0.3489
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2963 - val_accuracy: 0.8636 - val_loss: 0.3442
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2956 - val_accuracy: 0.8571 - val_loss: 0.3478
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2951 - val_accuracy: 0.8571 - val_loss: 0.3480
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2950 - val_accuracy: 0.8571 - val_loss: 0.3506
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8990 - loss: 0.2949 - val_accuracy: 0.8571 - val_loss: 0.3491
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2942 - val_accuracy: 0.8571 - val_loss: 0.3493

In [ ]:
def build_model(hp):

  model = Sequential()

  units = hp.Int('units',8,128)

  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='srk')

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.8311688303947449

Best val_accuracy So Far: 0.8376623392105103
Total elapsed time: 00h 00m 12s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 91}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6)

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7915 - loss: 0.4738
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4492
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7964 - loss: 0.4369
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4279
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8029 - loss: 0.4201
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8176 - loss: 0.4142
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8160 - loss: 0.4091
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8127 - loss: 0.4030
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8208 - loss: 0.3975
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8176 - loss: 0.3927
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8257 - loss: 0.3877
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8225 - loss: 0.3831
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8274 - loss: 0.3776
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8306 - loss: 0.3726
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8388 - loss: 0.3682
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8436 - loss: 0.3638
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8404 - loss: 0.3603
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8436 - loss: 0.3550
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8518 - loss: 0.3516
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8502 - loss: 0.3484
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8599 - loss: 0.3457
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8664 - loss: 0.3426
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8730 - loss: 0.3398
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8697 - loss: 0.3371
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8713 - loss: 0.3340
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8795 - loss: 0.3321
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8811 - loss: 0.3293
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8762 - loss: 0.3269
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8795 - loss: 0.3250
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8779 - loss: 0.3222
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8876 - loss: 0.3206
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8795 - loss: 0.3186
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3171
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3162
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3151
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8876 - loss: 0.3128
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8860 - loss: 0.3119
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3104
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8844 - loss: 0.3098
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8860 - loss: 0.3083
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8876 - loss: 0.3073
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3060
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8876 - loss: 0.3055
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.3047
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3033
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3031
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3022
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3011
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3004
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2995
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.2997
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.2983
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.2981
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.2972
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.2961
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8958 - loss: 0.2961
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.2949
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2943
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.2941
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.2935
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2923
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8974 - loss: 0.2925
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2920
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2914
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2907
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2912
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2894
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2893
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2890
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2877
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2875
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2866
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2865
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2858
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2856
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.2846
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2841
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2837
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9039 - loss: 0.2830
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8958 - loss: 0.2830
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2824
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2818
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2815
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2808
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2815
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9007 - loss: 0.2798
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2787
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2789
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8990 - loss: 0.2798
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2777
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9039 - loss: 0.2779
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8974 - loss: 0.2772
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2766
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2760

In [ ]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(89,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',1,10)):
    model.add(Dense(89,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='num_layers')

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=( X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.8571428656578064

Best val_accuracy So Far: 0.8766233921051025
Total elapsed time: 00h 00m 17s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.8567 - loss: 0.3543 - val_accuracy: 0.8766 - val_loss: 0.3307
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8632 - loss: 0.3327 - val_accuracy: 0.8766 - val_loss: 0.3286
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8664 - loss: 0.3212 - val_accuracy: 0.8636 - val_loss: 0.3274
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8762 - loss: 0.3087 - val_accuracy: 0.8571 - val_loss: 0.3585
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3038 - val_accuracy: 0.8571 - val_loss: 0.3361
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2979 - val_accuracy: 0.8506 - val_loss: 0.3286
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2883 - val_accuracy: 0.8636 - val_loss: 0.3275
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2830 - val_accuracy: 0.8506 - val_loss: 0.3478
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2773 - val_accuracy: 0.8312 - val_loss: 0.3678
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8909 - loss: 0.2749 - val_accuracy: 0.8571 - val_loss: 0.3471
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.2651 - val_accuracy: 0.8506 - val_loss: 0.3341
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2575 - val_accuracy: 0.8442 - val_loss: 0.3658
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2521 - val_accuracy: 0.8766 - val_loss: 0.3548
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2467 - val_accuracy: 0.8506 - val_loss: 0.3781
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2387 - val_accuracy: 0.8442 - val_loss: 0.3523
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2333 - val_accuracy: 0.8442 - val_loss: 0.3859
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2242 - val_accuracy: 0.8312 - val_loss: 0.3841
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2178 - val_accuracy: 0.8636 - val_loss: 0.3900
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9235 - loss: 0.2093 - val_accuracy: 0.8506 - val_loss: 0.3648
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.2066 - val_accuracy: 0.8442 - val_loss: 0.3883
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1988 - val_accuracy: 0.8506 - val_loss: 0.3673
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1940 - val_accuracy: 0.8247 - val_loss: 0.4167
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1889 - val_accuracy: 0.8377 - val_loss: 0.4094
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1748 - val_accuracy: 0.8312 - val_loss: 0.4222
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1705 - val_accuracy: 0.8506 - val_loss: 0.3960
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9528 - loss: 0.1615 - val_accuracy: 0.8312 - val_loss: 0.4184
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1652 - val_accuracy: 0.8117 - val_loss: 0.4305
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1534 - val_accuracy: 0.8442 - val_loss: 0.4298
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1446 - val_accuracy: 0.8182 - val_loss: 0.5110
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1390 - val_accuracy: 0.8182 - val_loss: 0.4664
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1266 - val_accuracy: 0.8117 - val_loss: 0.4669
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1327 - val_accuracy: 0.8247 - val_loss: 0.4432
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1186 - val_accuracy: 0.8312 - val_loss: 0.4920
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1272 - val_accuracy: 0.8052 - val_loss: 0.4865
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1076 - val_accuracy: 0.7987 - val_loss: 0.4931
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1084 - val_accuracy: 0.7922 - val_loss: 0.5063
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1035 - val_accuracy: 0.7792 - val_loss: 0.5221
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0919 - val_accuracy: 0.8377 - val_loss: 0.5558
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0902 - val_accuracy: 0.7857 - val_loss: 0.5227
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.0893 - val_accuracy: 0.8117 - val_loss: 0.5464
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0794 - val_accuracy: 0.7922 - val_loss: 0.5675
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0767 - val_accuracy: 0.8117 - val_loss: 0.5723
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0724 - val_accuracy: 0.7857 - val_loss: 0.6707
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9837 - loss: 0.0666 - val_accuracy: 0.7792 - val_loss: 0.6743
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9870 - loss: 0.0642 - val_accuracy: 0.7792 - val_loss: 0.5811
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9837 - loss: 0.0584 - val_accuracy: 0.7857 - val_loss: 0.6477
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9821 - loss: 0.0575 - val_accuracy: 0.7792 - val_loss: 0.5956
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9919 - loss: 0.0474 - val_accuracy: 0.8117 - val_loss: 0.6472
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9853 - loss: 0.0496 - val_accuracy: 0.8117 - val_loss: 0.7307
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9886 - loss: 0.0498 - val_accuracy: 0.8117 - val_loss: 0.6746
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9870 - loss: 0.0484 - val_accuracy: 0.7792 - val_loss: 0.6913
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0357 - val_accuracy: 0.7922 - val_loss: 0.7245
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0424 - val_accuracy: 0.7597 - val_loss: 0.7299
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0325 - val_accuracy: 0.7792 - val_loss: 0.7563
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0265 - val_accuracy: 0.7857 - val_loss: 0.7419
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0295 - val_accuracy: 0.8052 - val_loss: 0.7403
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0253 - val_accuracy: 0.7857 - val_loss: 0.7852
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0299 - val_accuracy: 0.7727 - val_loss: 0.8000
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0229 - val_accuracy: 0.7662 - val_loss: 0.8361
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0175 - val_accuracy: 0.7727 - val_loss: 0.9063
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0231 - val_accuracy: 0.7857 - val_loss: 0.8293
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0164 - val_accuracy: 0.8052 - val_loss: 0.7728
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0179 - val_accuracy: 0.7792 - val_loss: 0.8302
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0117 - val_accuracy: 0.7792 - val_loss: 0.8964
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0217 - val_accuracy: 0.7922 - val_loss: 0.8479
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0124 - val_accuracy: 0.7922 - val_loss: 0.8734
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0144 - val_accuracy: 0.7987 - val_loss: 0.9041
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0085 - val_accuracy: 0.7792 - val_loss: 1.0241
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0138 - val_accuracy: 0.7857 - val_loss: 0.9278
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0109 - val_accuracy: 0.7727 - val_loss: 0.9723
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0056 - val_accuracy: 0.7662 - val_loss: 1.0106
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0117 - val_accuracy: 0.7987 - val_loss: 1.1371
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0095 - val_accuracy: 0.7922 - val_loss: 0.9496
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.7727 - val_loss: 1.0654
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0083 - val_accuracy: 0.7792 - val_loss: 1.0300
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.7987 - val_loss: 1.0223
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.7727 - val_loss: 1.0449
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.7727 - val_loss: 1.1208
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.7792 - val_loss: 1.2415
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0111 - val_accuracy: 0.7792 - val_loss: 1.1090
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.7792 - val_loss: 1.2100
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.7792 - val_loss: 1.1693
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.8052 - val_loss: 1.1009
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0042 - val_accuracy: 0.7857 - val_loss: 1.1774
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.7857 - val_loss: 1.2369
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0050 - val_accuracy: 0.7792 - val_loss: 1.2919
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.7727 - val_loss: 1.3060
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0074 - val_accuracy: 0.7857 - val_loss: 1.2258
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0050 - val_accuracy: 0.7857 - val_loss: 1.2371
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.7727 - val_loss: 1.2909
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7857 - val_loss: 1.1805
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0089 - val_accuracy: 0.7922 - val_loss: 1.4574
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9967 - loss: 0.0080 - val_accuracy: 0.7857 - val_loss: 1.2872
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.5280e-04 - val_accuracy: 0.7727 - val_loss: 1.3433

In [ ]:
def build_model(hp):
  model = Sequential()
  counter = 0

  for i in range(hp.Int('num_layers',1,10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units' + str(i),8,128,8),
              activation=hp.Choice('activation' + str(i), values=['relu','tanh','sigmoid'] ),
              input_dim=8))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
              hp.Int('units' + str(i),8,128,8),
              activation=hp.Choice('activation' + str(i), values=['relu','tanh','sigmoid'] ),
              ))
    counter+=1
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','sgd','nadam','adadelta']),
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory = 'my_dir',
                        project_name='final1')

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 13s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7,
 'units0': 56,
 'activation0': 'relu',
 'dropout0': 0.8,
 'optimizer': 'adam',
 'units1': 120,
 'activation1': 'relu',
 'units2': 8,
 'activation2': 'sigmoid',
 'units3': 112,
 'activation3': 'relu',
 'units4': 72,
 'activation4': 'sigmoid',
 'units5': 104,
 'activation5': 'relu',
 'units6': 120,
 'activation6': 'sigmoid'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 34 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,y_train,epochs=200,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.7866 - loss: 0.4872 - val_accuracy: 0.8052 - val_loss: 0.4250
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4743 - val_accuracy: 0.8117 - val_loss: 0.4217
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4853 - val_accuracy: 0.8052 - val_loss: 0.4185
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4694 - val_accuracy: 0.8182 - val_loss: 0.4098
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4501 - val_accuracy: 0.8182 - val_loss: 0.4122
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4741 - val_accuracy: 0.8247 - val_loss: 0.4180
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4783 - val_accuracy: 0.8247 - val_loss: 0.4140
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4733 - val_accuracy: 0.8117 - val_loss: 0.4083
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4659 - val_accuracy: 0.8247 - val_loss: 0.4121
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4600 - val_accuracy: 0.8377 - val_loss: 0.4041
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4592 - val_accuracy: 0.8377 - val_loss: 0.4005
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4338 - val_accuracy: 0.8312 - val_loss: 0.4028
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4387 - val_accuracy: 0.8182 - val_loss: 0.3981
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4551 - val_accuracy: 0.8377 - val_loss: 0.3945
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4637 - val_accuracy: 0.8312 - val_loss: 0.4126
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4488 - val_accuracy: 0.8247 - val_loss: 0.4052
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4421 - val_accuracy: 0.8117 - val_loss: 0.4017
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4279 - val_accuracy: 0.8247 - val_loss: 0.4037
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4556 - val_accuracy: 0.8377 - val_loss: 0.4116
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4349 - val_accuracy: 0.7922 - val_loss: 0.4147
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4222 - val_accuracy: 0.7922 - val_loss: 0.4107
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4094 - val_accuracy: 0.7922 - val_loss: 0.4153
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3867 - val_accuracy: 0.8052 - val_loss: 0.4128
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.4160 - val_accuracy: 0.8052 - val_loss: 0.4074
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.4070 - val_accuracy: 0.8052 - val_loss: 0.4066
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.4089 - val_accuracy: 0.8312 - val_loss: 0.4049
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.4083 - val_accuracy: 0.8052 - val_loss: 0.4092
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3990 - val_accuracy: 0.7987 - val_loss: 0.4162
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4144
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3957 - val_accuracy: 0.7987 - val_loss: 0.4162
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3837 - val_accuracy: 0.8117 - val_loss: 0.4136
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.4075 - val_accuracy: 0.8247 - val_loss: 0.4043
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3928 - val_accuracy: 0.8247 - val_loss: 0.4014
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.4069 - val_accuracy: 0.8052 - val_loss: 0.4045
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.4024 - val_accuracy: 0.8052 - val_loss: 0.4058
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3936 - val_accuracy: 0.8052 - val_loss: 0.4063
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4131 - val_accuracy: 0.8506 - val_loss: 0.4053
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3885 - val_accuracy: 0.8117 - val_loss: 0.4116
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3874 - val_accuracy: 0.8117 - val_loss: 0.4160
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3720 - val_accuracy: 0.8052 - val_loss: 0.4151
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3808 - val_accuracy: 0.8052 - val_loss: 0.4138
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3705 - val_accuracy: 0.8377 - val_loss: 0.4096
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3800 - val_accuracy: 0.8182 - val_loss: 0.4124
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3891 - val_accuracy: 0.7987 - val_loss: 0.4289
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8404 - loss: 0.3758 - val_accuracy: 0.8182 - val_loss: 0.4240
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3987 - val_accuracy: 0.8052 - val_loss: 0.4191
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3877 - val_accuracy: 0.8182 - val_loss: 0.4141
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3848 - val_accuracy: 0.8117 - val_loss: 0.4181
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3885 - val_accuracy: 0.8247 - val_loss: 0.4137
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3580 - val_accuracy: 0.8182 - val_loss: 0.4171
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3920 - val_accuracy: 0.8182 - val_loss: 0.4188
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3704 - val_accuracy: 0.8247 - val_loss: 0.4208
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3711 - val_accuracy: 0.8247 - val_loss: 0.4146
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3605 - val_accuracy: 0.8247 - val_loss: 0.4199
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8371 - loss: 0.3915 - val_accuracy: 0.8247 - val_loss: 0.4207
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8371 - loss: 0.3917 - val_accuracy: 0.8182 - val_loss: 0.4216
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8404 - loss: 0.3737 - val_accuracy: 0.8247 - val_loss: 0.4214
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8420 - loss: 0.3827 - val_accuracy: 0.8312 - val_loss: 0.4223
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8485 - loss: 0.3632 - val_accuracy: 0.8247 - val_loss: 0.4218
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8599 - loss: 0.3630 - val_accuracy: 0.8377 - val_loss: 0.4143
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8436 - loss: 0.3862 - val_accuracy: 0.8247 - val_loss: 0.4184
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8502 - loss: 0.3645 - val_accuracy: 0.8247 - val_loss: 0.4167
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8469 - loss: 0.3908 - val_accuracy: 0.8247 - val_loss: 0.4146
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8648 - loss: 0.3505 - val_accuracy: 0.8247 - val_loss: 0.4133
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8599 - loss: 0.3579 - val_accuracy: 0.8247 - val_loss: 0.4163
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8518 - loss: 0.3795 - val_accuracy: 0.8312 - val_loss: 0.4109
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3791 - val_accuracy: 0.8247 - val_loss: 0.4215
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3677 - val_accuracy: 0.8247 - val_loss: 0.4215
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3595 - val_accuracy: 0.8377 - val_loss: 0.4154
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8388 - loss: 0.3601 - val_accuracy: 0.8247 - val_loss: 0.4051
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3757 - val_accuracy: 0.8247 - val_loss: 0.4044
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3666 - val_accuracy: 0.8247 - val_loss: 0.4182
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3483 - val_accuracy: 0.8247 - val_loss: 0.4103
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3546 - val_accuracy: 0.8312 - val_loss: 0.4121
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3643 - val_accuracy: 0.8247 - val_loss: 0.4220
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3522 - val_accuracy: 0.8247 - val_loss: 0.4125
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3407 - val_accuracy: 0.8312 - val_loss: 0.4204
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3591 - val_accuracy: 0.8247 - val_loss: 0.4107
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3443 - val_accuracy: 0.8312 - val_loss: 0.4107
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3538 - val_accuracy: 0.8377 - val_loss: 0.4106
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3468 - val_accuracy: 0.8312 - val_loss: 0.4193
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8388 - loss: 0.3763 - val_accuracy: 0.8571 - val_loss: 0.4058
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3526 - val_accuracy: 0.8312 - val_loss: 0.4154
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3579 - val_accuracy: 0.8312 - val_loss: 0.4130
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3351 - val_accuracy: 0.8312 - val_loss: 0.4190
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3395 - val_accuracy: 0.8377 - val_loss: 0.4102
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3420 - val_accuracy: 0.8506 - val_loss: 0.3993
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3477 - val_accuracy: 0.8377 - val_loss: 0.4130
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3726 - val_accuracy: 0.8312 - val_loss: 0.4058
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3561 - val_accuracy: 0.8312 - val_loss: 0.4102
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3446 - val_accuracy: 0.8377 - val_loss: 0.4096
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3404 - val_accuracy: 0.8377 - val_loss: 0.4146
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3565 - val_accuracy: 0.8312 - val_loss: 0.4072
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3416 - val_accuracy: 0.8377 - val_loss: 0.4131
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3501 - val_accuracy: 0.8312 - val_loss: 0.4042
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3261 - val_accuracy: 0.8377 - val_loss: 0.4119
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3510 - val_accuracy: 0.8377 - val_loss: 0.4003
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3341 - val_accuracy: 0.8312 - val_loss: 0.4071
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3376 - val_accuracy: 0.8312 - val_loss: 0.4097
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3386 - val_accuracy: 0.8312 - val_loss: 0.4142
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.3381 - val_accuracy: 0.8247 - val_loss: 0.4144
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3485 - val_accuracy: 0.8377 - val_loss: 0.3982
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3633 - val_accuracy: 0.8377 - val_loss: 0.4023
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3356 - val_accuracy: 0.8377 - val_loss: 0.4104
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3501 - val_accuracy: 0.8312 - val_loss: 0.4321
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3433 - val_accuracy: 0.8442 - val_loss: 0.4029
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3342 - val_accuracy: 0.8442 - val_loss: 0.4073
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.3256 - val_accuracy: 0.8442 - val_loss: 0.4137
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3471 - val_accuracy: 0.8377 - val_loss: 0.4105
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3273 - val_accuracy: 0.8442 - val_loss: 0.4128
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3234 - val_accuracy: 0.8571 - val_loss: 0.4023
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3261 - val_accuracy: 0.8442 - val_loss: 0.4116
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3227 - val_accuracy: 0.8312 - val_loss: 0.4049
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3386 - val_accuracy: 0.8442 - val_loss: 0.4124
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3355 - val_accuracy: 0.8377 - val_loss: 0.4126
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3368 - val_accuracy: 0.8442 - val_loss: 0.4081
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3554 - val_accuracy: 0.8442 - val_loss: 0.4077
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3563 - val_accuracy: 0.8312 - val_loss: 0.4165
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3267 - val_accuracy: 0.8442 - val_loss: 0.4003
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3366 - val_accuracy: 0.8377 - val_loss: 0.4259
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8713 - loss: 0.3256 - val_accuracy: 0.8506 - val_loss: 0.4042
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.8713 - loss: 0.3166 - val_accuracy: 0.8442 - val_loss: 0.4160
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.8713 - loss: 0.3060 - val_accuracy: 0.8506 - val_loss: 0.4121
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8697 - loss: 0.3348 - val_accuracy: 0.8442 - val_loss: 0.4167
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3287 - val_accuracy: 0.8442 - val_loss: 0.4160
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3192 - val_accuracy: 0.8442 - val_loss: 0.4158
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3393 - val_accuracy: 0.8442 - val_loss: 0.4090
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3309 - val_accuracy: 0.8442 - val_loss: 0.4058
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3338 - val_accuracy: 0.8442 - val_loss: 0.4126
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3403 - val_accuracy: 0.8442 - val_loss: 0.4051
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3206 - val_accuracy: 0.8442 - val_loss: 0.4096
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3140 - val_accuracy: 0.8571 - val_loss: 0.4068
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3115 - val_accuracy: 0.8442 - val_loss: 0.4195
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3212 - val_accuracy: 0.8442 - val_loss: 0.4222
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8713 - loss: 0.3292 - val_accuracy: 0.8571 - val_loss: 0.4155
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3214 - val_accuracy: 0.8442 - val_loss: 0.4276
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3300 - val_accuracy: 0.8377 - val_loss: 0.4142
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3182 - val_accuracy: 0.8506 - val_loss: 0.4104
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.3337 - val_accuracy: 0.8377 - val_loss: 0.4143
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.3185 - val_accuracy: 0.8312 - val_loss: 0.4238
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3395 - val_accuracy: 0.8377 - val_loss: 0.4122
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3421 - val_accuracy: 0.8442 - val_loss: 0.4198
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3285 - val_accuracy: 0.8442 - val_loss: 0.4131
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3234 - val_accuracy: 0.8442 - val_loss: 0.4219
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3368 - val_accuracy: 0.8442 - val_loss: 0.4211
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8550 - loss: 0.3377 - val_accuracy: 0.8442 - val_loss: 0.4143
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3200 - val_accuracy: 0.8377 - val_loss: 0.4223
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3271 - val_accuracy: 0.8442 - val_loss: 0.4041
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3435 - val_accuracy: 0.8377 - val_loss: 0.4141
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3164 - val_accuracy: 0.8442 - val_loss: 0.4194
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3342 - val_accuracy: 0.8442 - val_loss: 0.4095
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8599 - loss: 0.3401 - val_accuracy: 0.8442 - val_loss: 0.4005
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3362 - val_accuracy: 0.8377 - val_loss: 0.4095
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3310 - val_accuracy: 0.8377 - val_loss: 0.4123
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8746 - loss: 0.3177 - val_accuracy: 0.8442 - val_loss: 0.4121
Epoch 162/200